/*
 * script name : annotations.sql
 * description : accompanying script for the blog at
 *               https://www.werkenbijqualogy.com/blog/29/...
 */
clear screen
set serveroutput on size unlimited format wrapped
-- drop the table if it already exists
drop table if exists drivers
/
-- create a fully annotated table
create table if not exists drivers
(
  driverid      number       generated by default on null
                             as identity
                                        annotations ( primarykey
                                                    , display 'false')
, driver_number number  (  2 )          annotations ( "Permanent driver number"
                                                    , caption 'Driver number'
                                                    , display 'true'
                                                    , optional )
, code          varchar2(  3 )          annotations ( "Driver code e.g. 'VER'"
                                                    , caption 'Driver code'
                                                    , display 'true'
                                                    , non_unique )
, driver_name   varchar2( 32 ) not null annotations ( "Driver full name"
                                                    , caption 'Driver full name'
                                                    , display 'true'
                                                    , mandatory )
, dob           date           not null annotations ( "Driver date of birth"
                                                    , caption 'Driver date of birth'
                                                    , display 'true'
                                                    , mandatory )
, nationality   varchar2( 16 )          annotations ( "Driver nationality"
                                                    , caption 'Driver nationality'
                                                    , display 'true' )
)
annotations ( "access" 'Public' )
/
-- Add an annotation if it doesn't already exist
alter table drivers
modify nationality annotations ( add if not exists display 'true' )
/
-- Add or replace an annotation. Like an update
alter table drivers
annotations ( add or replace "access" 'Restricted' )
/
-- select the annotation names from the dictionary view
select annotation_name
from   user_annotations
/
-- select the annotation names with their corresponding values from the dictionary vies
select annotation_name
     , annotation_value
from   user_annotation_values
/
-- select the usage of the annotations with values from the dictionary view
select object_name
     , object_type
     , column_name
     , domain_name
     , domain_owner
     , annotation_name
     , annotation_value
from   user_annotations_usage
/
-- select the usage of the annotations with values from the dictionary view in JSON format
select object_type
     , object_name
     , column_name
     , json_serialize(
         json_arrayagg(
           json_object(
             annotation_name
           , annotation_value
           )
         )
       pretty ) in_jsonformat
from   user_annotations_usage
where  column_name = 'DRIVER_NUMBER'
group  by object_type
        , object_name
        , column_name
/
