/*
 * script name : if[not]exists.sql
 * description : accompanying script for the blog at 
 *               https://www.werkenbijqualogy.com/blog/26/if-[not]-exists
 */
-- The script to catch error that might occur when dropping objects
-- This can be extended to handle more object types
declare
  table_or_view_does_not_exist exception;
  pragma exception_init( table_or_view_does_not_exist, -00942 );
  sequence_does_not_exist      exception;
  pragma exception_init( sequence_does_not_exist, -02289 );
begin
  execute immediate q'[drop table mydrivers purge]';
exception
  when table_or_view_does_not_exist
    or sequence_does_not_exist then null; -- on purpose, hide any error
end;
/
-- In Oracle Database 23c these exceptions are handled by the database
drop table if exists mydrivers purge
/ 
-- Create a table
create table if not exists mydrivers
(
  driverid      number generated by default on null as identity,
  driver_number number(2),
  code          varchar2(3),
  driver_name   varchar2(32)
)
/
-- Create the table if it doesn't exist.
--  Be aware, if it does already exists, nothing happens.
create table if not exists mydrivers
(
  driverid      number generated by default on null as identity,
  driver_number number(2),
  code          varchar2(3),
  driver_name   varchar2(32),
  dob           date,
  nationality   varchar2(16)
)
/
